#version 450

layout(local_size_x=64) in;

#include "buffer_macros.comp"

readonly buffer X {
    uint[] x;
};

readonly buffer Target {
    T_BUFFER[] t;
};

buffer Y {
    uint[] y;
};

layout(push_constant) uniform PushConsts {
    uint n;
};

void main() {
    uint gid = gl_GlobalInvocationID.x;
    if (gid < n) {
        if (x[gid] == BUFFER_LOAD(t, gid)) {
            atomicAdd(y[0], 1);
        }
    }
}
